// Session cards (post-form sessions page). Real speakers from the AI Unpacked agenda.
export const SESSIONS = [
  {
    id: 1,
    track: "10:45 AM",
    time: "10:45 — 11:15 AM",
    title: "AI, but make it useful.",
    blurb: "An opening keynote on what AI actually changes for the business in front of you — not the one in the headlines.",
    speaker: "Hitesh Mahajan",
    role: "Opening Keynote",
    tag: "Keynote",
    accent: "blue",
  },
  {
    id: 2,
    track: "11:18 AM",
    time: "11:18 — 11:48 AM",
    title: "Building with what you have.",
    blurb: "Practical AI for small teams, family businesses, and shops that don't have a tech department.",
    speaker: "Kayuyu Mwaura",
    role: "Speaker · Featured",
    tag: "Practice",
    accent: "red",
  },
  {
    id: 3,
    track: "11:52 AM",
    time: "11:52 — 12:20 PM",
    title: "Customers, in their own words.",
    blurb: "Using AI to listen to your customers at scale — and turn what you hear into the next decision.",
    speaker: "Reena Goore",
    role: "Speaker · Featured",
    tag: "Growth",
    accent: "blue",
  },
  {
    id: 4,
    track: "12:20 PM",
    time: "12:20 — 12:45 PM",
    title: "Fireside Q&A",
    blurb: "An unscripted half-hour. Bring your hardest question about AI in your business — we'll answer it together.",
    speaker: "Nafisa Teja",
    role: "Hosted Conversation",
    tag: "Live Q&A",
    accent: "red",
  },
  {
    id: 5,
    track: "12:45 PM",
    time: "12:45 — 12:55 PM",
    title: "Digital literacy for seniors.",
    blurb: "A short, warm session on bringing the people you love along for the ride — at any age.",
    speaker: "Zahiba Mawji",
    role: "Community Talk",
    tag: "Community",
    accent: "blue",
  },
  {
    id: 6,
    track: "1:15 PM",
    time: "1:15 PM onwards",
    title: "Buffet, networking & mingle.",
    blurb: "Find the speakers, find the founders, find your next conversation. The team is at the back table.",
    speaker: "Open networking",
    role: "Open mingle",
    tag: "Networking",
    accent: "red",
  },
];

export const COMPANY_SIZES = [
  "Just me",
  "2 — 10",
  "11 — 50",
  "51 — 200",
  "200+",
];
